# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.cert.checkAttributes", false);
user_pref("app.update.cert.requireBuiltIn", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1366100392);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1366100512);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1372675971);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1366100632);
user_pref("app.update.url", "");
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 367415);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.slowStartup.averageTime", 1200);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://www.aakb.dk/");
user_pref("browser.startup.homepage_override.buildID", "20130512194445");
user_pref("browser.startup.homepage_override.mstone", "21.0");
user_pref("browser.syncPromoViewsLeft", 4);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1367667164438");
user_pref("datareporting.policy.firstRunTime", "1367580764438");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1067);
user_pref("datareporting.sessions.current.main", 46);
user_pref("datareporting.sessions.current.sessionRestored", 1160);
user_pref("datareporting.sessions.current.startTime", "1372675978734");
user_pref("datareporting.sessions.current.totalTime", 7);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1367580753567,\"a\":0,\"t\":16649,\"c\":true,\"m\":1850,\"fp\":7695,\"sr\":11816}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1372675958270,\"a\":1,\"t\":18,\"c\":true,\"m\":505,\"fp\":1479,\"sr\":13852}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"21.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"21.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"langpack-da@firefox.mozilla.org\":{\"version\":\"21.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-da@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.6,globalmenu%40ubuntu.com:4.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:21.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1360793368000,\"rdfTime\":1353361961000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1369823071000,\"rdfTime\":1368389811000},\"langpack-da@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-da@firefox.mozilla.org.xpi\",\"mtime\":1368391083000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/globalmenu@ubuntu.com\",\"mtime\":1369823066000,\"rdfTime\":1368389805000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1368391088000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1368391088000}}}]");
user_pref("extensions.lastAppVersion", "21.0");
user_pref("extensions.lastPlatformVersion", "21.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130512194445");
user_pref("gecko.mstone", "21.0");
user_pref("idle.lastDailyNotification", 1366100782);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1366100782);
user_pref("places.history.expiration.transient_current_max_pages", 26090);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1366100782);
user_pref("toolkit.startup.last_success", 1372675978);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1375267974);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
