#!/usr/bin/env python

"""
%Description%
"""

__author__ = ""
__copyright__ = "Copyright 2017, Magenta Aps"
__credits__ = [""]
__license__ = "GPL"
__version__ = "0.0.1"
__maintainer__ = ""
__email__ = ""
__status__ = "Production/Test/Development"
