#!/usr/bin/env python

"""
%Description%
"""

import csv_writer

__author__ = "Danni Als"
__copyright__ = "Copyright 2017, Magenta Aps"
__license__ = "GPL"
__version__ = "0.0.1"
__maintainer__ = "Danni Als"
__email__ = "danni@magenta.dk"
__status__ = "Production"

# securityEventCode, Tec sum, Raw data
csv_data = []
# securityEventCode (security problem id)
csv_data.append("%SECURITY_PROBLEM_UID%")

# Tec sum
csv_data.append("Ping warning.")

# Raw data
csv_data.append("Nothing to worry about. Just a ping warning.")

csv_writer.write_data(csv_data)

