# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1324372646);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1324372646);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1324372646);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 317461);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://www.aakb.dk/");
user_pref("browser.startup.homepage_override.buildID", "20111115184056");
user_pref("browser.startup.homepage_override.mstone", "rv:8.0");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 6);
user_pref("extensions.enabledAddons", "langpack-da@firefox.mozilla.org:8.0,globalmenu@ubuntu.com:2.0.1,ubufox@ubuntu.com:1.0,langpack-en-GB@firefox.mozilla.org:8.0,langpack-en-ZA@firefox.mozilla.org:8.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:8.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-da@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-da@firefox.mozilla.org.xpi\",\"mtime\":1321398357000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/globalmenu@ubuntu.com\",\"mtime\":1322737525000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/ubufox@ubuntu.com\",\"mtime\":1322737608000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1321398358000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1321398358000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-8.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1322737530000}}}]");
user_pref("extensions.lastAppVersion", "8.0");
user_pref("extensions.lastPlatformVersion", "8.0");
user_pref("extensions.pendingOperations", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 95178);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1326964530);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
