#!/bin/sh
### BEGIN INIT INFO
# Provides:          bibos-broadcast-server
# Required-Start:    $local_fs $remote_fs $network $named
# Required-Stop:     $local_fs $remote_fs $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop BibOS broadcast server
### END INIT INFO

set -e

. /lib/lsb/init-functions

test -f /etc/default/rcS && . /etc/default/rcS

DAEMON_SCRIPT=/usr/share/bibos/local_server/broadcast_server.py

case $1 in
	start)
	    $DAEMON_SCRIPT start
	;;
	stop)
	    $DAEMON_SCRIPT stop
	;;
	restart)
	    $DAEMON_SCRIPT restart
	;;
	*)
	    echo "Usage: /etc/init.d/bibos-broadcast-server {start|stop|restart}"
	    exit 1
	;;
esac
